# Generated by Django 4.2 on 2025-03-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('acucess', models.IntegerField()),
                ('fun', models.IntegerField()),
                ('many', models.IntegerField()),
                ('view', models.IntegerField()),
            ],
        ),
    ]
