# Generated by Django 4.2 on 2025-03-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_content_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='status',
        ),
    ]
